### ISSUE TITLE
catch tools.hypernode.com 404

### ISSUE THREAD

**Issue by aurmil** [integer-net/DevDashboard#4]
hello

got this error:

Warning: file_get_contents(https://tools.hypernode.com/patches/community/1.9.2.4): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
  in .modman/DevDashboard/app/code/community/IntegerNet/DevDashboard/Model/RequiredPatches/Api.php on line 13

indeed, https://tools.hypernode.com/patches/community/1.9.2.4 page does not exist

regards

**Comment by gwillem** [comment]
Thanks for reporting, fixed that (and the auto updater).
